version: '3'

services:
    db:
        image: postgres
      
    web:
        build: .
        volumes:
            - .: C:\Users\eyara\Desktop\Web Development\containers\airline
        ports:
            - "8000:8000"